repositories:
  - name: groundhog2k
    url: https://groundhog2k.github.io/helm-charts/

helmDefaults:
  wait: true
  timeout: 300

releases:
  - name: postgres
    namespace: iiot-dev
    chart: groundhog2k/postgres
    version: 1.6.8
    values:
      - values/postgres.yaml

  - name: timescaledb
    namespace: iiot-dev
    chart: groundhog2k/postgres
    version: 1.6.8
    values:
      - values/timescaledb.yaml
