spring:
  application:
    name: iiot-core-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/iiot_config
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  timescale:
    datasource:
      url: jdbc:postgresql://localhost:5433/iiot_timeseries
      username: ${TIMESCALEDB_USER}
      password: ${TIMESCALEDB_PASSWORD}
      driver-class-name: org.postgresql.Driver


server:
  port: 8081